version: '3.1'

services:
  pepproxy:
    image: iotcrawler/pep-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
        - "1027:1027"
    restart: unless-stopped
    environment:
        # PEP proxy endpoint: protocol+ip+port
        # HOST NO admitted: 0.0.0.0, localhost, 127.0.0.1
        - PEP_ENDPOINT=https://155.54.95.170:1027