version: '3.1'

services:
  pepproxy:
    image: iotcrawler/pep-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
        - "1027:1027"
    restart: unless-stopped
    environment:
        #Broker protocol. Admitted values: "http","https"
        - target_protocol=https
        #Broker host.
        - target_host=155.54.95.248
        - target_port=9090

        #Validate Capability token using blockchain: Admitted values: "0: No use; 1:Use"
        - blockchain_usevalidation=1

        #BlockChain protocol. Admitted values: "http","https"
        - blockchain_protocol=http
        #BlockChain host.
        - blockchain_host=195.37.154.24
        - blockchain_port=8000

        # PEP proxy endpoint: protocol+ip+port
        # HOST NO admitted: 0.0.0.0, localhost, 127.0.0.1
        - PEP_ENDPOINT=https://155.54.95.170:1027